# Funding options for this project
# You can uncomment and add your funding platforms

# github: [polykrate]
# patreon: your-username
# ko_fi: your-username
# custom: ["https://your-donation-link.com"]

